export const GIROS_COMERCIALES = [
  'Gastronomía',
  'Jardinería y Paisajismo',
  'Tecnología',
  'Comercio',
  'Salud y Bienestar',
  'Educación',
  'Construcción',
  'Manufactura',
  'Servicios Profesionales',
  'Transporte y Logística',
  'Agricultura',
  'Arte y Cultura',
  'Otro',
]